config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#welcome'
  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do

    resources :subscribes, only: [:create, :index, :delete] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end  
  end

  mount KepplerBlog::Engine, :at => '/', as: 'blog'

  get '/about/:user_permalink', to:'frontend#about_user', as: :about_user
  get 'index', to:'frontend#index', as: :index

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
	layout 'layouts/frontend/application'
  before_filter :set_subscribe
	
  def index
  	@posts = KepplerBlog::Post.where(public: true).first(5)
    @user_elis = User.find(2)
    @user_aure = User.find(3)
  	@categories = KepplerBlog::Category.all
  end

  def about_user
    @user = User.find_by_permalink(params[:user_permalink])
    @posts = KepplerBlog::Post.where(user_id: @user.id).all
  end

  def welcome
    @user = User.all
  end

  private

  def set_subscribe
    @subscribe = Subscribe.new
  end

  
end

app/views/frontend/pages/_about.html.haml
- if @categories.count > 5
	.container-categories.multiple-items
		- @categories.each do |category|
			%p #{category.name}

.row.container-about
	.col-lg-4{style:"padding: 0;"}
		.container-about-elis
			%p.container-about-elis-name
				Soy Elis
			= link_to about_user_path(@user_elis.permalink) do
				= image_tag "#{(request.ssl? ? 'https://secure' : 'http://www')}.gravatar.com/avatar/#{Digest::MD5.hexdigest @user_elis.email}?s=160", class: "container-about-elis-photo"
			%p.container-about-elis-description
				Me llamo Daniela Elisa Vega Angulo, tengo 26 años soy Venezolana, soñadora y Viajera empedernida, con ganas de seguir conociendo los múltiples destinos y culturas que me ofrece el mundo en especial mi país.


	.col-lg-4{style:"padding: 0;"}
		.container-about-logo
			= image_tag "frontend/logo.png"


	.col-lg-4{style:"padding: 0;"}
		.container-about-aure
			%p.container-about-aure-name
				Soy Aure
			= link_to about_user_path(@user_aure.permalink) do
				= image_tag "#{(request.ssl? ? 'https://secure' : 'http://www')}.gravatar.com/avatar/#{Digest::MD5.hexdigest @user_aure.email}?s=160", class: "container-about-aure-photo"
			%p.container-about-aure-description
				Soy Aureivys Mendez una Venezolana, publicista y apasionada por la comida que ama las diferencias culturales. Lectora y escritora, creyente de las distintas perspectivas de la vida, seguidora de los viajes.

:javascript
	$('.multiple-items').slick({
		infinite: true,
		slidesToShow: 5,
		slidesToScroll: 1,
		infinite: true,
		centerMode: true
	});

app/views/frontend/pages/_home.html.haml
.container-home
	.container-home-title
		%p ¡Viajando por el mundo!

app/views/frontend/pages/_last_blog.html.haml
- if @posts.count > 2
	.container-last-blog
		%p.container-last-blog-title Lo ultimo en el Blog
		.container-last-blog-divisor

		.container-last-blog-posts.row#margin
			- @posts.each_with_index do |post, index|
				- if index > 1
					.col-lg-4
						.container-last-blog-posts-post{style:"left: 15px;"}
							= link_to "/blog/category/#{post.category.name}" do
								%p.container-last-blog-posts-post-category{style:"background: #{post.category.color}"} #{post.category.name}

							= link_to "/blog/#{post.permalink}" do
								.container-last-blog-posts-post-photo{ style: "background-image: url(#{post.image});" }
								%p.container-last-blog-posts-post-title #{post.title.truncate(32)}
								%p.container-last-blog-posts-post-subtitle #{post.subtitle.truncate(35)}
								.container-last-blog-posts-post-divisor
							= image_tag "#{(request.ssl? ? 'https://secure' : 'http://www')}.gravatar.com/avatar/#{Digest::MD5.hexdigest post.user.email}?s=60", class: "avatar"
							= link_to about_user_path(post.user.permalink) do
								%p.container-last-blog-posts-post-user	#{post.user.name}
							%p.container-last-blog-posts-post-date	#{I18n.l @posts[1].created_at, format: '%B %d, %Y'}
		
					
				

app/views/frontend/pages/_news.html.haml
.container-recents
	%p.container-recents-title Lo más reciente
	.container-recents-divisor
	.row.posts-recents 
		- @posts.each_with_index do |post, index|
			- if index < 2
				.post-recent.col-lg-6
					= link_to "blog/#{post.permalink}" do
						.post-recent-image{ style: "background-image: linear-gradient(0deg, rgba(30, 33, 33, 0.8) 1%, rgba(32, 32, 32, 0.09) 84%), url(#{post.image});" }
							.post-recent-items 
								%p.post-recent-items-category{style:"background: #{post.category.color}"} #{post.category.name}
								%p.post-recent-items-title #{post.title.truncate(35)}
								%p.post-recent-items-subtitle #{post.subtitle.truncate(35)}
								.col-lg-6{style:"padding:0;"}
									= image_tag "#{(request.ssl? ? 'https://secure' : 'http://www')}.gravatar.com/avatar/#{Digest::MD5.hexdigest post.user.email}?s=60", class: "avatar"
									= link_to about_user_path(post.user.permalink) do
										%p.post-recent-items-user #{post.user.name}
								.col-lg-6
									%p.post-recent-items-date	#{I18n.l post.created_at, format: '%B %d, %Y'}
						