config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#welcome'
  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do

    resources :subscribes, only: [:create, :index, :delete] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end  
  end

  mount KepplerBlog::Engine, :at => '/', as: 'blog'

  get '/about/:user_permalink', to:'frontend#about_user', as: :about_user
  get 'index', to:'frontend#index', as: :index

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

end

app/models/subscribe.rb
#Generado por keppler
require 'elasticsearch/model'
class Subscribe < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates_uniqueness_of :email
  validates_presence_of :email
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create, message: "No es un email valido" }
  
  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:email] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      email:  self.email.to_s,
    }.as_json
  end

end
#Subscribe.import

app/controllers/subscribes_controller.rb
#Generado con Keppler.
class SubscribesController < ApplicationController  
  before_filter :authenticate_user!, except: [:create]
  layout 'admin/application'
  load_and_authorize_resource except: [:create]
  before_action :set_subscribe, only: [:show, :edit, :update, :destroy]

  # GET /subscribes
  def index
    subscribes = Subscribe.searching(@query).all
    @objects, @total = subscribes.page(@current_page), subscribes.size
    redirect_to subscribes_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end


  # POST /subscribes
  def create
    @subscribe = Subscribe.new(subscribe_params)
    @subscribe.save

    respond_to do |format|
      format.js
    end
  end

  # DELETE /subscribes/1
  def destroy
    @subscribe.destroy
    redirect_to subscribes_url, notice: 'Subscribe was successfully destroyed.'
  end

  def destroy_multiple
    Subscribe.destroy redefine_ids(params[:multiple_ids])
    redirect_to subscribes_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscribe
      @subscribe = Subscribe.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def subscribe_params
      params.require(:subscribe).permit(:email)
    end
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/subscribes/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Permite visualizar todos los correos electronicos de los usuarios registrados a la pagina web.

app/views/subscribes/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to subscribes_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @subscribe do |f|
					.row
						= f.input :email

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/subscribes/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Subscribe
			= link_to edit_subscribe_path(@subscribe), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @subscribe.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.email")
			.display-value= @subscribe.email
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/subscribes/_listing.html.haml
%tr{ id: "row-#{subscribe.id}" }
	- if can? :destroy_multiple, Subscribe
		%td.item-check{style:"width: 10%"}
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{subscribe.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{subscribe.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{subscribe.id}" }

		%td{style:"width: 30%"}
			%span
				= subscribe.email
								
	%td{style:"width: 5%"}		
	

app/views/subscribes/create.js.haml
$('.container-footer-suscribe-icon-load').hide();
$('#errores').show();

- if @subscribe.errors.any?
	$('.success').hide();
	$('.error').show();
	$('#errores-messages-error').text('#{@subscribe.errors.messages[:email].first}');

-else
	$('.error').hide();
	$('.success').show();
	$('#subscribe_email').val("");
	$('#errores-messages-success').text('Su correo a sido registrado con exito');

app/views/subscribes/edit.html.haml
= title "Subscribes - editar | #{@subscribe.id}"
= render 'form'

app/views/subscribes/index.html.haml
= title("Subscribes - Listado")
.listing.col.l9.m12.s12
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |subscribe|
				= render 'listing', subscribe: subscribe
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado subscribes.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

app/views/subscribes/new.html.haml
= title "Subscribes - Nuevo"
= render 'form'

app/views/subscribes/show.html.haml
= title "Subscribes | #{@subscribe.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Subscribe
				= link_to subscribe_path(@subscribe), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Subscribe
				= link_to edit_subscribe_path(@subscribe), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to subscribes_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.id")
					.display-value.fs-body-1.tc-black-2= @subscribe.id.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.email")
					.display-value.fs-body-1.tc-black-2= @subscribe.email.to_s.humanize

app/views/subscribes/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@subscribe.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");